# ==============================================================================
# --------------------------------- CONTAINERS ---------------------------------
# ==============================================================================

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - vitejs
      - nestjs
    restart: always
    tty: true
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/certs:/etc/nginx/certs
      - ./containers/nginx/logs:/var/log/nginx
    networks:
      app:
        ipv4_address: 172.20.0.2

  vitejs:
    image: node:19-alpine
    container_name: vitejs
    depends_on:
      - nestjs
    restart: always
    working_dir: /app
    volumes:
      - ./containers/vitejs:/app
    networks:
      app:
        ipv4_address: 172.20.0.3
    environment:
      - VITE_FRONT_URL
      - VITE_BACK_URL
    entrypoint: ["/bin/sh", "-c" , "npm install && npm run dev -- --host "]

  nestjs:
    image: node:19-alpine
    container_name: nestjs
    depends_on:
      - postgres
    restart: always
    working_dir: /app
    volumes:
      - ./containers/nestjs:/app
    networks:
      app:
        ipv4_address: 172.20.0.4
      database:
    environment:
      - FRONT_URL
      - BACK_URL
      - CLIENT_ID
      - CLIENT_SECRET
      - CALLBACK_URL
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - JWT_KEY
      - OTP_CRYPTO_PASSWORD
      - OTP_CRYPTO_IV
    entrypoint: ["/bin/sh", "-c" , "npm install && npm run start:dev"]

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      database:
        ipv4_address: 172.18.0.2
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER

volumes:
  postgres_db:

# ==============================================================================
# ---------------------------------- NETWORKS ----------------------------------
# ==============================================================================

networks:
  app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

  database:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
